In [148]:
import boto3
import pandas as pd
from datetime import datetime, timedelta
import pytz
from user_agents import parse
import time
import psycopg2
from sqlalchemy import create_engine

In [142]:
# Connect to Minio using the S3 protocol
s3 = boto3.resource("s3",
                    endpoint_url="http://172.26.0.3:9000",
                    aws_access_key_id="minioadmin",
                    aws_secret_access_key="miniopassword")
local_tz = pytz.timezone('Asia/Karachi')
now = datetime.now(local_tz)

# Get the current time and construct the prefix string
# now = datetime.now()
year, month, day, hour = now.year, now.month, now.day, now.hour - 1
prefix = f"year={year:04d}/month={month:02d}/day={day:02d}/hour={hour:02d}"

# Get a list of CSV file names in the directory
bucket_name = 'test-bucket'

while True:
        objects = s3.Bucket(bucket_name).objects.filter(Prefix=f'{prefix}/FULL')
        if any(objects):
            break
        print('Waiting for FULL file to appear...')
        time.sleep(60)

objects = s3.Bucket(bucket_name).objects.filter(Prefix=prefix)
csv_files = [obj.key for obj in objects if obj.key.endswith('.csv')]


# Read the CSV files into a single Pandas DataFrame
dfs = []
for file_name in csv_files:
    obj = s3.Object(bucket_name, file_name)
    body = obj.get()['Body']
    df = pd.read_csv(body, index_col=0)
    dfs.append(df)
combined_df = pd.concat(dfs, ignore_index=True)

# Parse the user agent strings into device type and browser columns
ua_series = combined_df['user_agent'].apply(parse)
combined_df['device_type'] = ua_series.apply(lambda ua: ua.device.family)
combined_df['browser'] = ua_series.apply(lambda ua: ua.browser.family)

In [143]:
combined_df

,timestamp,user_cookie,site,user_agent,device_type,browser
0,2023-02-24T01:54:58.031581,81355b13141a4913bf8e334188c53988,lifestyle,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,Mac,Safari
1,2023-02-24T01:28:22.006755,21cd7dcae768400f90b46a9df6eeeb65,fashion,Mozilla/5.0 (Linux; Android 10; SM-G996U Build...,Samsung SM-G996U,Android
2,2023-02-24T01:03:17.081137,a02dbf9ed11b4930ac6551cc903ee87c,health,Mozilla/5.0 (compatible; Googlebot/2.1; +http:...,Spider,Googlebot
3,2023-02-24T01:56:46.043366,e136cce2ba3c433e849e68f53086263d,fashion,Mozilla/5.0 (Linux; Android 12; SM-S906N Build...,Samsung SM-S906N,Chrome Mobile WebView
4,2023-02-24T01:04:04.034622,603197d2cde0408a8c692e6d22c07235,fashion,Mozilla/5.0 (Linux; Android 12; SM-S906N Build...,Samsung SM-S906N,Chrome Mobile WebView
...,...,...,...,...,...,...
774496,2023-02-24T01:57:25.005079,7ffe377a316a4638aa50710a5f9d1318,main,Mozilla/5.0 (Linux; Android 10; SM-G996U Build...,Samsung SM-G996U,Android
774497,2023-02-24T01:04:07.026294,27e43fe20e4848a486c38248f3a6a464,sport,Mozilla/5.0 (Linux; Android 12; SM-S906N Build...,Samsung SM-S906N,Chrome Mobile WebView
774498,2023-02-24T01:15:04.038342,62c107ec8f7e4144a9b20b0dc9f94262,tech,"Mozilla/5.0 (iPhone14,3; U; CPU iPhone OS 15_0...",iPhone,Mobile Safari
774499,2023-02-24T01:32:30.073743,5d35abf471724b2a8ec078cac6d48965,tech,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,Mac,Safari
774500,2023-02-24T01:12:25.043132,7f095651da134581a692009a8019b047,tech,Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like M...,iPhone,Chrome Mobile iOS

In [144]:
# Calculate the sum of page views and unique users by site, device type, and browser
metrics_df = combined_df.groupby(['site', 'device_type', 'browser']).agg({
    'user_cookie': 'nunique',
    'timestamp': 'count',
})
metrics_df = metrics_df.rename(columns={'user_cookie': 'unique_users', 'timestamp': 'page_views'})

In [145]:
metrics_df

                                                 unique_users  page_views
site     device_type      browser
business Mac              Safari                         7418       10024
         Other            Chrome                         7434       10012
                          Edge                           7420       10050
                          Firefox                        7436       10119
         Samsung SM-G973U Chrome Mobile                  7444        9988
...                                                       ...         ...
tech     Samsung SM-G996U Android                        7491       10189
         Samsung SM-S906N Chrome Mobile WebView          7429       10103
         Spider           Googlebot                      7565       10299
         iPhone           Chrome Mobile iOS              7412       10017
                          Mobile Safari                 11367       20299

[70 rows x 2 columns]

In [149]:
# Replace the placeholders with the appropriate values for your database
db_host = "your_database_host"
db_name = "your_database_name"
db_user = "your_database_user"
db_password = "your_database_password"
db_port = "your_database_port"

# Create a connection to the PostgreSQL database
conn = psycopg2.connect(
    host=db_host,
    database=db_name,
    user=db_user,
    password=db_password,
    port=5432
)

# Create a SQLAlchemy engine for the connection
engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

# Create a table for the metrics
table_name = 'metrics_table' # Replace with the name of the table you want to create
with engine.connect() as con:
    con.execute(f"CREATE TABLE {table_name} (site TEXT, device_type TEXT, browser TEXT, unique_users INTEGER, page_views INTEGER)")

# Write the dataframe to the table
metrics_df.to_sql(table_name, engine, if_exists='append', index=False)

# Close the connection
conn.close()

OperationalError: invalid integer value "your_database_port" for connection option "port"